### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by murugeshmanthiramoorthi** [geosolutions-it/docker-geoserver#87]
I need to get the output from Geoserver through HTTPS rather than HTTP. I followed the following procedure recommended by Geoserver.
https://docs.geoserver.org/stable/en/user/security/tutorials/cert/index.html#configure-tomcat-for-ssl

I was not able to recreate it on the docker container. But I was possible on my machine. Is it possible to add it to the dockerfile or is there any other resource that I can follow to d o the same?

Thanks in advance.

**Comment by randomorder** [comment]
Hi @murugeshmanthiramoorthi 

Yes, it's doable, should be just a matter of mappping the relevant files to the correct locations

One way is using Dockerfile [ADD](https://docs.docker.com/engine/reference/builder/#add) or [COPY](https://docs.docker.com/engine/reference/builder/#copy) statements and rebuilding the image.

Alternatively you can [bind mount](https://docs.docker.com/storage/bind-mounts/) the files to the final location and avoid rebuilding the image but it is not as portable of a solution because the files live on the hosting machine.

**Comment by murugeshmanthiramoorthi** [comment]
@randomorder 

Thanks a lot for the information. I will try to rebuild the dockerfile.
